### ISSUE TITLE
Crashing Agent with 101, UNO, Zero...

### ISSUE THREAD

**Issue by 00alis** [arduino/arduino-create-agent#155]
I've (unfortunately) found a way to make the Agent crash consistently on Chrome 58.0.3029.110 (64-bit), Mac OSX El Capitan 10.11.6, Agent 1.1.55. 

How to replicate:
- connect a 101 or a UNO, or a Zero
- upload example AnalogInOutSerial.ino
- open the Serial Monitor and let it print for a few seconds
- disconnect the board from cable abruptly
- agent crashes

**Comment by facchinm** [comment]
Backtrace of the event:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x486bcd]

goroutine 125 [running]:
panic(0x9248c0, 0xc42000c110)
	/home/jenkins/go/src/runtime/panic.go:500 +0x1a1
encoding/json.(*encodeState).marshal.func1(0xc4202a9e30)
	/home/jenkins/go/src/encoding/json/encode.go:272 +0x1b9
panic(0x9248c0, 0xc42000c110)
	/home/jenkins/go/src/runtime/panic.go:458 +0x243
encoding/json.(*encodeState).string(0xc42019c0b0, 0x0, 0x7, 0x1, 0x7)
	/home/jenkins/go/src/encoding/json/encode.go:852 +0x6d
encoding/json.stringEncoder(0xc42019c0b0, 0x8f7ea0, 0xc42027e0f0, 0x98, 0x100)
	/home/jenkins/go/src/encoding/json/encode.go:564 +0x228
encoding/json.(*structEncoder).encode(0xc4202c21b0, 0xc42019c0b0, 0x9365c0, 0xc42027e0f0, 0x99, 0x930100)
	/home/jenkins/go/src/encoding/json/encode.go:601 +0x253
encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc42019c0b0, 0x9365c0, 0xc42027e0f0, 0x99, 0xc420270100)
	/home/jenkins/go/src/encoding/json/encode.go:615 +0x64
encoding/json.(*encodeState).reflectValue(0xc42019c0b0, 0x9365c0, 0xc42027e0f0, 0x99, 0x100)
	/home/jenkins/go/src/encoding/json/encode.go:307 +0x82
encoding/json.(*encodeState).marshal(0xc42019c0b0, 0x9365c0, 0xc42027e0f0, 0x420100, 0x0, 0x0)
	/home/jenkins/go/src/encoding/json/encode.go:280 +0xb8
encoding/json.Marshal(0x9365c0, 0xc42027e0f0, 0xc42027e0f0, 0x9365c0, 0xc42027e0f0, 0x0, 0x7)
	/home/jenkins/go/src/encoding/json/encode.go:145 +0x8f
main.(*BufferflowTimed).Init.func1(0xc420218880)
	/home/jenkins/workspace/Create_agent_devel/src/github.com/arduino/arduino-create-agent/bufferflow_timed.go:38 +0x258
created by main.(*BufferflowTimed).Init
	/home/jenkins/workspace/Create_agent_devel/src/github.com/arduino/arduino-create-agent/bufferflow_timed.go:52 +0xd7
```
