### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by hannobraun** [arduino/arduino-create-agent#205]
After pulling the latest changes to `devel`, I get the following runtime error when running the agent:

```
$ ./arduino-create-agent.exe
time="2018-02-01T05:44:43+01:00" level=info msg="Version:x.x.x-dev"
time="2018-02-01T05:44:43+01:00" level=info msg="Hostname: DESKTOP-NSSTGSU"
time="2018-02-01T05:44:43+01:00" level=info msg="Garbage collection is on using Standard mode, meaning we just let Golang determine when to garbage collect."
time="2018-02-01T05:44:43+01:00" level=info msg="You specified a serial port regular expression filter: usb|acm|com\n"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x1 pc=0x8d8380]

goroutine 5 [running]:
github.com/arduino/arduino-create-agent/vendor/github.com/go-ini/ini.(*File).GetSection(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/Users/hb/go/src/github.com/arduino/arduino-create-agent/vendor/github.com/go-ini/ini/file.go:113 +0x70
main.getConfigs.func1(0xc042330680, 0x72, 0xd16a00, 0xc04233d020, 0x0, 0x0, 0xc0422c7d20, 0x72)
        C:/Users/hb/go/src/github.com/arduino/arduino-create-agent/trayicon.go:87 +0x24d
path/filepath.walk(0xc042330680, 0x72, 0xd16a00, 0xc04233d020, 0xc042002640, 0x0, 0x0)
        C:/Go/src/path/filepath/path.go:351 +0x88
path/filepath.walk(0xc04233cd80, 0x60, 0xd16a00, 0xc04233cde0, 0xc042002640, 0x0, 0x0)
        C:/Go/src/path/filepath/path.go:376 +0x41b
path/filepath.walk(0xc04232b140, 0x57, 0xd16a00, 0xc04232b1a0, 0xc042002640, 0x0, 0x0)
        C:/Go/src/path/filepath/path.go:376 +0x41b
path/filepath.walk(0xc04232ae40, 0x53, 0xd16a00, 0xc04232aea0, 0xc042002640, 0x0, 0x0)
        C:/Go/src/path/filepath/path.go:376 +0x41b
path/filepath.walk(0xc0422d8370, 0x4c, 0xd16a00, 0xc0422da180, 0xc042002640, 0x0, 0x0)
        C:/Go/src/path/filepath/path.go:376 +0x41b
path/filepath.walk(0xc0422d8000, 0x41, 0xd16a00, 0xc0422cdf20, 0xc042002640, 0x0, 0x0)
        C:/Go/src/path/filepath/path.go:376 +0x41b
path/filepath.walk(0xc04200e380, 0x3a, 0xd16a00, 0xc0421ca300, 0xc042002640, 0x0, 0x20)
        C:/Go/src/path/filepath/path.go:376 +0x41b
path/filepath.Walk(0xc04200e380, 0x3a, 0xc042002640, 0x3a, 0x40fc0f)
        C:/Go/src/path/filepath/path.go:398 +0x153
main.getConfigs(0x950d40, 0xc0420025e0, 0x0)
        C:/Users/hb/go/src/github.com/arduino/arduino-create-agent/trayicon.go:97 +0xfb
main.setupSysTrayReal()
        C:/Users/hb/go/src/github.com/arduino/arduino-create-agent/trayicon.go:125 +0x1e3
github.com/arduino/arduino-create-agent/vendor/github.com/getlantern/systray.Run.func1(0xa877a8)
        C:/Users/hb/go/src/github.com/arduino/arduino-create-agent/vendor/github.com/getlantern/systray/systray.go:53 +0x53
created by github.com/arduino/arduino-create-agent/vendor/github.com/getlantern/systray.Run
        C:/Users/hb/go/src/github.com/arduino/arduino-create-agent/vendor/github.com/getlantern/systray/systray.go:54 +0xbc
```

I'm simply doing a `go build`, then run the compiled binary. The system is Windows 10, 64-bit.

I'm looking into it to see if I can find out what's happening.

**Comment by umbynos** [comment]
The current version handles read errors
