### ISSUE TITLE
panic: open templates/nofirefox.html: no such file or directory

### ISSUE THREAD

**Issue by ghost** [arduino/arduino-create-agent#221]
When I executed `./arduino-create-agent`, I got an error.
```
INFO[0000] Version:x.x.x-dev
INFO[0000] Hostname: focalhot-Pro.local
INFO[0000] Garbage collection is on using Standard mode, meaning we just let Golang determine when to garbage collect.
INFO[0000] You specified a serial port regular expression filter: usb|acm|com

INFO[0000] Your serial ports:
INFO[0000] 	{/dev/cu.wchusbserial14140     0x7523 0x1A86  false}

panic: open templates/nofirefox.html: no such file or directory

goroutine 34 [running]:
html/template.Must(0x0, 0x48cafa0, 0xc4201ac9c0, 0x0)
	/usr/local/go/src/html/template/template.go:360 +0x54
github.com/arduino/arduino-create-agent/vendor/github.com/gin-gonic/gin.(*Engine).LoadHTMLFiles(0xc4201f01c0, 0xc4201ae960, 0x1, 0x1)
	/Users/mokuai/go/src/github.com/arduino/arduino-create-agent/vendor/github.com/gin-gonic/gin/gin.go:137 +0x11f
main.main.func1()
	/Users/mokuai/go/src/github.com/arduino/arduino-create-agent/main.go:223 +0xc73
created by main.main
	/Users/mokuai/go/src/github.com/arduino/arduino-create-agent/main.go:277 +0x65
mokuaideMacBook-Pro:arduino-create-agent mokuai$
```
OS / golang version
```
go version go1.8.3 darwin/amd64
macOS 10.13.3
```

**Comment by umbynos** [comment]
Could you please try the latest agent version?
