### ISSUE TITLE
Runtime Error: Invalid Memory Address or Nil Pointer Dereference

### ISSUE THREAD

**Issue by Magpie720** [arduino/arduino-create-agent#989]
### Describe the problem

I encountered a runtime error when trying to install and run the Arduino Cloud Agent. after running Arduino_Cloud_Agent.exe, icon does not appear in the system tray, no error window, just nothing happens. need to enter command in the PowerShell to check for the error.
Below is error output:
```
Arduino_Cloud_Agent.exe : panic: runtime error: invalid memory address or nil pointer dereference
위치 줄:1 문자:1
+ & "C:\Users\KJH\AppData\Roaming\ArduinoCloudAgent\Arduino_Cloud_Agent ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (panic: runtime ...ter dereference:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

[signal 0xc0000005 code=0x1 addr=0x20 pc=0x1505918]

goroutine 7 [running]:
fyne.io/systray.(*winTray).setIcon(0x1cf38e0, {0xc0006a0060?, 0x1aa93?})
        C:/Users/runneradmin/go/pkg/mod/fyne.io/systray@v1.10.0/systray_windows.go:238 +0xb8
fyne.io/systray.SetIcon({0x1c95d80?, 0x0?, 0x0?})
        C:/Users/runneradmin/go/pkg/mod/fyne.io/systray@v1.10.0/systray_windows.go:901 +0xbe
fyne.io/systray.SetTemplateIcon(...)
        C:/Users/runneradmin/go/pkg/mod/fyne.io/systray@v1.10.0/systray_windows.go:912
github.com/arduino/arduino-create-agent/systray.(*Systray).start(0x1cf3380)
        D:/a/arduino-create-agent/arduino-create-agent/systray/systray_real.go:53 +0x34
fyne.io/systray.Register.func2()
        C:/Users/runneradmin/go/pkg/mod/fyne.io/systray@v1.10.0/systray.go:98 +0x2f
created by fyne.io/systray.Register in goroutine 1
        C:/Users/runneradmin/go/pkg/mod/fyne.io/systray@v1.10.0/systray.go:96 +0xb1
```

### To reproduce

Attempt to run the Arduino Cloud Agent using the following command on PowerShell
`& "C:\Users\KJH\AppData\Roaming\ArduinoCloudAgent\Arduino_Cloud_Agent.exe" 2>&1 | Out-String -Stream`
The error appears immediately upon execution.

### Expected behavior

Agent should run

### Arduino Create Agent version

ArduinoCloudAgent-1.6.1-windows-amd64

### Operating system

Windows

### Operating system version

Win11

### Browser

Chrome 

### Browser version

127.0.6533.100

### Additional context

I have tried various versions of the Arduino Cloud Agent, from 1.6.1 to 1.3.9. Before each reinstallation, I deleted the ArduinoCloudAgent and ArduinoCreateAgent folders. The same error occurs across all versions.

The issue occurs with both the amd64 and i386 versions.

I modified the config.ini file setting crashreport = true, but no crash report was generated.

I disabled both the firewall and antivirus software, and I ran the agent with administrator privileges, but same problem happens.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-create-agent/issues?q=)
- [X] I verified the problem still occurs when using the latest version
- [X] My report contains all necessary details

**Comment by bigjoncoop** [comment]
**I am suddenly I'm having the same issue as well**

Windows 11

Arduino Cloud Agent has worked fine for a very long time. Then just the other day I realized that my board was not showing up in Arduino cloud.

When I run the Arduino Cloud agent nothing happens and the icon does not appear on the right hand side of my Taskbar. In task manager it doesn't show it's running either.

I've tried to uninstall it and reinstall it as well as trying to remove the folders in appdata/roaming, but this hasn't helped either...

I tried running the command the OP showed in the original post using Powershell and I am having a slightly different outcome.

After running:

& "C:\Users\xxx\AppData\Roaming\ArduinoCloudAgent\Arduino_Cloud_Agent.exe" 2>&1 | Out-String -Stream

The powershell prompt changes to:

>>
>>

I'm not exactly sure what that means or if that's a good thing or not but regardless the Arduino Cloud agent is not working.
